# Generated by Django 4.0.4 on 2022-05-01 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandOfProduct',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, verbose_name='کد')),
                ('Name', models.CharField(max_length=20, verbose_name='برند')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfProduct',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, verbose_name='کد')),
                ('Name', models.CharField(max_length=20, verbose_name='نوع')),
                ('Parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.typeofproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, verbose_name='نام محصول')),
                ('Price', models.IntegerField(verbose_name='قیمت')),
                ('Description', models.TextField(verbose_name='توضیحات')),
                ('Slug', models.SlugField()),
                ('Active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.brandofproduct', verbose_name='برند')),
                ('Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.typeofproduct', verbose_name='نوع')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
