# Generated by Django 4.0.4 on 2022-05-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_typeofproduct_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandofproduct',
            options={'verbose_name': 'برند', 'verbose_name_plural': 'برندها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': ' محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='typeofproduct',
            options={'verbose_name': 'نوع محصول', 'verbose_name_plural': 'انواع محصول'},
        ),
        migrations.AddField(
            model_name='product',
            name='Img',
            field=models.ImageField(default='noimage.png', upload_to='images/', verbose_name='عکس محصول'),
        ),
        migrations.AlterModelTable(
            name='brandofproduct',
            table='T_Brand',
        ),
        migrations.AlterModelTable(
            name='product',
            table='T_Product',
        ),
        migrations.AlterModelTable(
            name='typeofproduct',
            table='T_TypeOfProduct',
        ),
    ]
