# Generated by Django 4.0.4 on 2022-05-01 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_options_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at', '-updated_at'], 'verbose_name': ' محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Active',
            new_name='Is_Active',
        ),
    ]
