# Generated by Django 4.0.4 on 2022-05-01 21:11

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('num_brand', django.db.models.manager.Manager()),
            ],
        ),
    ]
