# Generated by Django 4.0.4 on 2022-05-02 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='کد')),
                ('Name', models.CharField(max_length=20, verbose_name='نام ویژگی')),
            ],
        ),
        migrations.CreateModel(
            name='PropertiesOfProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, verbose_name='مقدار ویژگی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='نام کالا')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.property', verbose_name='نام ویژگی')),
            ],
        ),
    ]
