# Generated by Django 4.0.4 on 2022-05-03 08:37

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_product_property'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('num_brand', django.db.models.manager.Manager()),
            ],
        ),
    ]
