# Generated by Django 4.0.4 on 2022-05-03 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_product_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
    ]
