# Generated by Django 4.0.4 on 2022-05-03 09:12

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_product_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('admin_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
