# Generated by Django 4.0.4 on 2022-05-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_product_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertiesofproduct',
            options={'verbose_name': 'ویژگی محصول', 'verbose_name_plural': 'ویژگی های محصولات'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': ' ویژگی', 'verbose_name_plural': 'ویژگی ها'},
        ),
        migrations.AlterModelTable(
            name='propertiesofproduct',
            table='T_PropertiesOfProduct',
        ),
        migrations.AlterModelTable(
            name='property',
            table='T_Property',
        ),
    ]
